### PR TITLE
don't update the base image

### PR DESCRIPTION
**Pull request by wkloucek**

### CODE REVIEW

**Comment by xoxys** [comment]
Tbh we should drop this golang wait-for crap and replace it by somethhing like this https://github.com/thegeeklab/wait-for. We can ok course copy this repo into oncloud space or keep the wait-for golang foo but its freaking outdated. In this case we should also maintain our own fork and build binaries instead of these multistage images.

**Comment by xoxys** [comment]
And why do we need to build su-exec and gomplate on our own?

**Comment by xoxys** [comment]
My bad, gomplate and su-exec are just fetchted in the build image and copied into the final one :facepalm: IMO we should drop the entire build part, download requirements in the final image directly and replace the outdated wait-for service

**Review by xoxys — APPROVED** [review]

**Comment by wkloucek** [comment]
@xoxys I removed the golang modification for now. 
I would like to keep the syntax of `wait-for` (`wait-for -it github.com:80`) since I don't know who uses it and don't want to break that. Forking `https://github.com/alioygur/wait-for` and doing small maintenance and binary releases seem like a small task. So I would go for that.

**Comment by xoxys** [comment]
Sure, also fine with that :+1:

**Pull request merged**
