### PR TITLE
Update gomplate for arm compatibility

### PR DESCRIPTION
**Pull request by JKawohl**
This should resolve https://github.com/owncloud/enterprise/issues/3968

more reference: 
https://github.com/hairyhenderson/gomplate/issues/821

@xoxys I am not certain about any unwanted side-effects on our containers.

### CODE REVIEW

**Comment by xoxys** [comment]
Me neither. So LGTM, but you have to fix the checksum partially.

**Comment by xoxys** [comment]
And you have to rebase to master.

**Comment by JKawohl** [comment]
@jnweiger may I please  ask you to take a look why the build is failing? I do not understand the output 
```

Unpacking libc6:armhf (2.31-0ubuntu9) over (2.30-0ubuntu3) ...
--
964 | tar: ./control: Cannot utime: Operation not permitted
965 | tar: ./md5sums: Cannot utime: Operation not permitted
966 | tar: ./shlibs: Cannot utime: Operation not permitted
967 | tar: ./symbols: Cannot utime: Operation not permitted
968 | tar: ./triggers: Cannot utime: Operation not permitted
969 | tar: .: Cannot utime: Operation not permitted
970 | tar: Exiting with failure status due to previous errors
971 | dpkg-deb: error: tar subprocess returned error exit status 2
972 | dpkg: error processing archive /var/cache/apt/archives/libcrypt1_1%3a4.4.10-10ubuntu4_armhf.deb (--unpack):
973 | dpkg-deb --control subprocess returned error exit status 2
974 | Errors were encountered while processing:
975 | /var/cache/apt/archives/libcrypt1_1%3a4.4.10-10ubuntu4_armhf.deb
976 | E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by jnweiger** [comment]
Sorry for the late reply.
You run into https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1867675
My workaround was to skip any attempts of 20.04 builds on arm32.

@dschmidt updated gomplate to 3.7.0 in https://github.com/owncloud-docker/ubuntu/pull/42
That obsoetes the update to 3.6.0 here. Right?

**Comment by wkloucek** [comment]
supersed by https://github.com/owncloud-docker/ubuntu/pull/47

**Pull request closed without merging**
