### PR TITLE
feat: add ubuntu 22.04

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud-docker/ubuntu/212/5/2
```
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
The command '/bin/sh -c apt-get update -y &&   apt-get install -y     ca-certificates     bash     vim     curl     wget     rsync     procps     apt-utils     apt-transport-https     iputils-ping     bzip2     unzip     cron     git-core     sshpass     tree     jq     gnupg     libnss-wrapper &&   apt-get clean &&   rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100

exit status 100
```

I restarted and got this error again. What is going on?

**Comment by phil-davis** [comment]
I separated the commands. The problem is https://drone.owncloud.com/owncloud-docker/ubuntu/215/5/2
```
Step 11/19 : RUN apt-get update -y
 ---> Running in cbb78db00805
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [61.3 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [61.0 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [84.2 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [90.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [157 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [97.5 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [68.6 kB]
Fetched 20.8 MB in 3s (7583 kB/s)
Reading package lists...
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
The command '/bin/sh -c apt-get update -y' returned a non-zero code: 100
exit status 100
```

An ordinary `apt-get update` fails. Why is that?

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud-docker/ubuntu/216/5/2

I moved `apt-get update` to earlier in the script, just in case something needed to be got up-to-date earlier, before other commands. But it fails the same:
```
Step 5/20 : RUN apt-get update -y
 ---> Running in a4ecfcaf46c4
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [90.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [61.0 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [97.5 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [157 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [68.6 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [61.3 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [84.2 kB]
Fetched 20.8 MB in 2s (13.1 MB/s)
Reading package lists...
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
The command '/bin/sh -c apt-get update -y' returned a non-zero code: 100
exit status 100
```

@xoxys do you have any ideas?

This passes in the ARM pipelines.

**Comment by phil-davis** [comment]
@xoxys I am struggling to think what I did wrong here - do you have any clue?

**Comment by xoxys** [comment]
That might be related to the current docker version or OS version of the drone runners. As I'm still not at work this week, I can look into it next week. The AMD image builds fine on my local machine.

**Comment by xoxys** [comment]
@phil-davis fixed, CI agents updated to ubuntu-20.04 builds working again.

**Comment by xoxys** [comment]
Sorry, I was wrong and was looking on the latest tag -.- needs further investigating....

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud-docker/ubuntu/223/5/2
```
Fetched 21.2 MB in 1s (19.9 MB/s)
Reading package lists...
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
The command '/bin/sh -c apt-get update -y &&   apt-get install -y     ca-certificates     bash     vim     curl     wget     rsync     procps     apt-utils     apt-transport-https     iputils-ping     bzip2     unzip     cron     git-core     sshpass     tree     jq     gnupg     libnss-wrapper &&   apt-get clean &&   rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100
exit status 100
```
Same problem as before. Needs investigation. No big hurry right now.

**Review by xoxys — APPROVED** [review]
@phil-davis Fixed. Feel free to merge.

**Comment by xoxys** [comment]
The failed link check is expected, if you are ready let me know, then we can "force" merge it.

**Comment by phil-davis** [comment]
I pushed an update to the release date in the changelog - will merge when CI finishes.

**Comment by phil-davis** [comment]
> The failed link check is expected, if you are ready let me know, then we can "force" merge it.

I am happy - please force merge.

**Pull request merged**
